### PR TITLE
Prevent timeout on reaching keyserver in some ubuntus

### PR DESCRIPTION
**Pull request by mhenrixon**
So I have a strange issue with all my ubuntu VMs that they won't find any keyserver that is missing port and protocol.

This ensures that all ubuntus can find the keyserver

### CODE REVIEW

**Comment by jagregory** [comment]
There are a lot of commits in this PR, can you cut it down to just the keyserver fixes?

**Comment by mhenrixon** [comment]
hah sorry about that, I forgot to checkout a branch. I will fix that and of course.

**Comment by mhenrixon** [comment]
This should do the trick no?

**Comment by jagregory** [comment]
Looks good! Thanks.

**Pull request merged**
